name: djatayucoffee
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.10.17
  provider: ^6.1.0
  file_picker: ^6.2.3
  intl: ^0.18.1
  flutter_launcher_icons: "^0.13.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.1.0  # tambahkan versi terbaru yang tersedia


flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.png" 
  min_sdk_android: 21 
  

flutter:
  uses-material-design: true

  assets:
    - assets/bg.jpeg
    - assets/logo.png
